### ISSUE TITLE
How to get demo presented as pictures in the README files 

### ISSUE THREAD

**Issue by yohannes-taye** [Mathux/TEMOS#1]
Hi dear authors, 

I would like to start by saying thank you for your amazing work. I managed to train the model and run the sample.py file. But the results I got were only a [.npy] file. Am I doing something wrong or are there additional steps I need to take to produce the similar results presented in the teaser figures?

**Comment by Mathux** [comment]
Hello @yohannes-taye,

Thanks for your interest, and for being one of the first TEMOS users.

I just release the files needed to render the motions (as in the figures of the paper). 
You can now use ``render.py`` after using ``sample.py`` (see more explanation in README.md).
