### ISSUE TITLE
Problems related to blender installation

### ISSUE THREAD

**Issue by LinghaoChan** [Mathux/TEMOS#10]
Thanks for your tutorial of the blender installation.  
There are some problems. The [command](https://github.com/Mathux/TEMOS/blob/a4e7e3ee303ab4cb6ce7e15ac763cf8e3d604f88/README.md?plain=1#L186):
```bash
blender --background --python-expr "import sys; import os; print('\nThe path to the installation of python of blender can be:'); print('\n'.join(['- '+x for x in sys.path if 'python' in (file:=os.path.split(x)[-1]) and not file.endswith('.zip')]))"
```
works wrongly on my MacOS.

It returns me a path `/Applications/Blender.app/Contents/Resources/3.2/python/lib/python3.10`. However, this is not an executable python path. I changed it into `/Applications/Blender.app/Contents/Resources/3.2/python/bin/python3.10`, which works well on my MacOS. Is it a bug of the provided command? 

This is the problem I met with here, peers with the same problem can solve it similarly. I hope the authors can modify this command. Thanks~

**Comment by Mathux** [comment]
Thanks for the issue, I updated the README with this command, which seems to work better.

```bash
blender --background --python-expr "import sys; import os; print('\nThe path to the installation of python of blender can be:'); print('\n'.join(['- '+x.\
replace('/lib/python', '/bin/python') for x in sys.path if 'python' in (file:=os.path.split(x)[-1]) and not file.endswith('.zip')]))"
```
