### ISSUE TITLE
The config in rendering

### ISSUE THREAD

**Issue by LinghaoChan** [Mathux/TEMOS#11]
When rendering all the data (`folder=FOLDER` setting), it seems that the `infolder` parameter in file `configs/render.yaml` should  be set as `true`.

**Comment by Mathux** [comment]
Thanks for your issue, it was indeed not very clear. As suggested, I changed ``infolder``to true by default and update the ``README.md``.
To give you some explanation, if ``infolder`` is set to false, the ``folder`` parameter is expected to be the folder of the experiment and not the folder with the npys: it rely on ``split`` and ``jointstype`` parameters to find the folder of npys.
It is indeed more natural that ``folder`` is directly the folder with npys.
