### ISSUE TITLE
APE and AVE_pose metric calculation

### ISSUE THREAD

**Issue by angelacast135** [Mathux/TEMOS#13]
Hey, Thank you so much for sharing this project. 
I was trying to run the training code and saw what I think is a little bug here
https://github.com/Mathux/TEMOS/blob/ea12cf6b22122aa5be95bbd75fcc374c0f42398a/temos/model/base.py#L45 

Should it have a .mean()?
`dico.update({f"Metrics/{metric}": value.mean() for metric, value in metrics_dict.items()})`
Otherwise, I get this error 
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/35589196/186333555-23aaa562-1f5e-46fe-98c7-98d42ce7ebd6.png">

Please let me know if I'm right or not :) 

Thanks!

**Comment by Mathux** [comment]
Hello @angelacast135,

Thanks for the pointer, I just got the error myself when upgrading the packages. 
I just fixed this issue by removing the logging of the arrays (APE_pose, APE_joints, AVE_pose, AVE_joints) as it is not necessary (and now not supported apparently). I am already logging the means. It solves the problem.
  
Commit: https://github.com/Mathux/TEMOS/commit/40410d925600182fd20395ebe439c432f0e17fe4
