### ISSUE TITLE
Normalize Values Calculation 

### ISSUE THREAD

**Issue by KevinQian97** [Mathux/TEMOS#15]
Hi, 
Congrats and thanks for releasing your work!
May I double check how did you calculate the mean&std in normalization step? (e.g. the file under ${path.deps}/transforms/rots2rfeats/smplvelp/${.pose_rep}/${data.dataname}).

Thanks!

**Comment by Mathux** [comment]
Hi @KevinQian97,

You can use the following cmd line:
```bash
python compute_stats.py data=DATANAME
```
and it should work as expected.

**Comment by KevinQian97** [comment]
Hi @Mathux ,

Thanks so much for your fast reply!
