### ISSUE TITLE
Updated evaluation code used for ghosh et al

### ISSUE THREAD

**Issue by chinnusai25** [Mathux/TEMOS#18]
Hey, is it possible for you to share the updated evaluation code which you used to calculate the metrics on ghosh et al model

**Comment by Mathux** [comment]
Hi,

I update the README.md. You can use the command line: ``bash prepare/download_previous_works.sh`` to download the motion generated from previous work. Then ``python evaluate.py folder=previous_work/ghosh`` to evaluate on ghosh et al.
