### ISSUE TITLE
How to visualize the result?

### ISSUE THREAD

**Issue by lucasjinreal** [Mathux/TEMOS#2]
I didn't see any script which visualize the result nor any pretrained models...

**Comment by Mathux** [comment]
Hello @jinfagang,

I just release the files needed to render the motions (as in the figures of the paper).
You can now use render.py after using sample.py (see more explanation in README.md).

I will soon publish the pre-trained models, I can keep you updated.

**Comment by Mathux** [comment]
Hello @jinfagang, 
Pre-trained models and instructions are now available. Please check the README.md.
