### ISSUE TITLE
Rendering SMPLX motion sequence of AMASS

### ISSUE THREAD

**Issue by linjing7** [Mathux/TEMOS#20]
Hi, thanks for your excellent work. I follow your instruction and successfully visualize the SMPL motion sequence of AMASS. I try to visualize the SMPLX motion sequence and save the meshes in a format of (T, 10475, 3). And then, I render the meshes with `render.py` using blender. However, the rendering result is as follows:
Do you have any idea about this issue? 
<img width="673" alt="image" src="https://user-images.githubusercontent.com/70081899/209435985-b8c99c4b-6a8f-4a58-88b8-4c84a21e5714.png">

**Comment by Mathux** [comment]
Hi @linjing7,

Yes, I see where the problem come from. The faces of the mesh (triangles) are the one with SMPL topology and not SMPL-X (I did not support it yet).

To solve the problem, you just have to save the SMPL-X faces into a file (let's say smplx.faces), and load the file here instead:
https://github.com/Mathux/TEMOS/blob/4768fe5dc8f23f442b6af0cad1c6b084f85c7058/temos/render/blender/meshes.py#L19

To do so automatically, you just need to change the config there:
https://github.com/Mathux/TEMOS/blob/4768fe5dc8f23f442b6af0cad1c6b084f85c7058/configs/render.yaml#L50

Or specify in the command line, like ``faces_path=smplh/smplx.faces``

Tell me if you need help to get the SMPL-X faces, but it should be easy to find.

**Comment by linjing7** [comment]
Hi, thanks for your timely reply! It works and I can get correct result now.
