### ISSUE TITLE
How to fit the generated motion of KIT dataset to smpl

### ISSUE THREAD

**Issue by qiqiApink** [Mathux/TEMOS#22]
I have generated motion with 21 joints 3d positions and I wonder how to fit them to smpl. It seems that the codes provided only work on HumanML3D.

**Comment by qiqiApink** [comment]
I have generated motion with 21 joints 3d positions and I wonder how to fit them to smpl. It seems that the codes provided only work on HumanML3D.

**Comment by Mathux** [comment]
Hello @qiqiApink,

In this work, we do not fit skeletons to SMPL. We generate the motions directly in the SMPL format (see the ``kit-amass-rot`` data loader option). 

If you want to generate skeletons and fit them to SMPL, you can check other works (like MDM where they use SMPLify optimisation algorithm on top of the generated motions).
