### ISSUE TITLE
Skeleton structure and indexes

### ISSUE THREAD

**Issue by Dean-UQ** [Mathux/TEMOS#23]
Hi,

I notice that the skeleton used in the KIT dataset has 21 joints. I would like to know what is the detailed skeleton structure and body joint indexes of KIT.

Many Thanks for your reply and help.

**Comment by Mathux** [comment]
Hello @Dean-UQ,

The skeleton joints location of KIT processed with MMM are the following:
["root", "BP", "BT", "BLN", "BUN", "LS", "LE", "LW", "RS", "RE", "RW", "LH", "LK", "LA", "LMrot", "LF", "RH", "RK", "RA", "RMrot", "RF"]

<img width="243" alt="Screenshot 2023-03-11 at 15 02 04" src="https://user-images.githubusercontent.com/25257425/224489017-376cbb36-be72-4bc6-9809-d3bb89410fc1.png">

Best
