### ISSUE TITLE
"_fke.csv"

### ISSUE THREAD

**Issue by 1390806607** [Mathux/TEMOS#25]
kit dataset originally had "_fke.csv" file, or was it generated by data preprocessing? If it was generated by preprocessing, could you please send me the code

**Comment by maplect** [comment]
I got the same question, did you fix it? I can only find files end with "_quat.csv" and "_quat.fke"

**Comment by Mathux** [comment]
Hello both @1390806607 @maplect,

As explained in the readme, you should run the code from Ghosh et al or JL2P to process the data. It will create the files which ends with "fke.csv". The code links are in the readme.

Tell me if you have any issues

**Comment by maplect** [comment]
> Hello both @1390806607 @maplect,
> 
> As explained in the readme, you should run the code from Ghosh et al or JL2P to process the data. It will create the files which ends with "fke.csv". The code links are in the readme.
> 
> Tell me if you have any issues

Many thanks for your rapid reply. I got the problem, I firstly run the code from [JL2P](https://github.com/chahuja/language2pose), and the output of `find datasets/kit/* -name . -o -prune | head -20` is

`datasets/kit/00001_annotations.json
datasets/kit/00001_meta.json
datasets/kit/00001_mmm.xml
datasets/kit/00001_quat.csv
datasets/kit/00001_quat.fke
datasets/kit/00001_quat.rifke
datasets/kit/00001_raw.c3d
datasets/kit/00002_annotations.json
datasets/kit/00002_meta.json
datasets/kit/00002_mmm.xml
datasets/kit/00002_quat.csv
datasets/kit/00002_quat.fke
datasets/kit/00002_quat.rifke
datasets/kit/00002_raw.c3d
datasets/kit/00003_annotations.json
datasets/kit/00003_meta.json
datasets/kit/00003_mmm.xml
datasets/kit/00003_quat.csv
datasets/kit/00003_quat.fke
datasets/kit/00003_quat.rifke`

While I run the code from [Ghosh](https://github.com/anindita127/Complextext2animation), the output of `find datasets/kit/* -name . -o -prune | head -20` is

`datasets/kit/00001_annotations.json
datasets/kit/00001_ax.csv
datasets/kit/00001_fke.csv
datasets/kit/00001_meta.json
datasets/kit/00001_mmm.xml
datasets/kit/00001_quat.csv
datasets/kit/00001_raw.c3d
datasets/kit/00001_rifke.csv
datasets/kit/00002_annotations.json
datasets/kit/00002_ax.csv
datasets/kit/00002_fke.csv
datasets/kit/00002_meta.json
datasets/kit/00002_mmm.xml
datasets/kit/00002_quat.csv
datasets/kit/00002_raw.c3d
datasets/kit/00002_rifke.csv
datasets/kit/00003_annotations.json
datasets/kit/00003_ax.csv
datasets/kit/00003_fke.csv
datasets/kit/00003_meta.json`
and I can find the files which end with "fke.csv". So I think there are some differences between these two data generation script.

**Comment by Mathux** [comment]
Hi @maplect,
I will remove JL2P from the README then, thanks for pointing it out!
