### ISSUE TITLE
How to add texture to the rendered image?

### ISSUE THREAD

**Issue by linjing7** [Mathux/TEMOS#26]
Hi, thanks for your excellent work. I wonder how to add a texture to the rendered image to obtain a more realistic result like the following image:
<img width="840" alt="image" src="https://user-images.githubusercontent.com/70081899/225011258-b86f7ab9-0b6b-411a-b44d-f2e6ffb34383.png">
<img width="867" alt="image" src="https://user-images.githubusercontent.com/70081899/225011648-ec853729-781a-4beb-aeea-c6152924713c.png">

**Comment by Mathux** [comment]
Hello @linjing7,

I think these texture come from Meshcapade: https://github.com/Meshcapade/SMPL_texture_samples/tree/main/Textured_Mesh_samples

I don't use them in this repo and I don't have any code to use them.
Maybe you can ask the authors of this figure for help.
