### ISSUE TITLE
start and end positions 

### ISSUE THREAD

**Issue by j-p-e** [Mathux/TEMOS#32]
thanks for this interesting work. When creating video sequences, the code ties the start and end positions tied to be the same for every prompt. Is it easy to relax this so that a prompt 'a person is sitting' has them sitting throughout all frames, rather than standing, moving to sitting, and back again ? Not sure if changing the 'canonicalize' setting would help with this. I do not need to evaluate metrics.

I am using this type of command (together with blender video creation). 
python3 interact.py text="a person is sitting" folder=out saving=out length=50 jointstype=vertices

I have copied the config.yaml, hydra.yaml and overrides.yaml from pretrained model kit-amass-rot\1cp6dwpa to out/.hydra

**Comment by Mathux** [comment]
I don't really understand your question, what do you mean by "the code ties the start and end positions tied to be the same for every prompt."?
