### ISSUE TITLE
How to train TEMOS on other datasets?

### ISSUE THREAD

**Issue by fyyakaxyy** [Mathux/TEMOS#33]
Hello, thank you very much for providing such an excellent project.
TEMOS was trained on the KIT-ML dataset, but this dataset is too small. I would like to ask how to train TEMOS on other datasets? For example, the BABEL dataset and the HumanML3D dataset.
Looking forward to your reply, thank you!

**Comment by Mathux** [comment]
Hello @fyyakaxyy,

I am about to release the full code of [TMR](http://mathis.petrovich.fr/tmr), where I took the opportunity to rewrite TEMOS. The code will be way easier to follow, it will train x2 faster (the text embeddings are precomputed) and will be compatible with KIT-ML, HumanML3D and BABEL datasets. 

I should release all this next week, I will let you know.

**Comment by fyyakaxyy** [comment]
Thank you for your answer. I will continue to follow your work!
