### ISSUE TITLE
how to accelerate render speed when using long sequences with blender

### ISSUE THREAD

**Issue by YongtaoGE** [Mathux/TEMOS#36]
Hi, thanks for your great work. @Mathux 

I tried to visualize amass annotations using Blender. I wonder if it is possible to render a long sequence of SMPL-X annotations parallelly to accelerate the rendering speed.

I am not very familiar with the blender. Could you give me some hints on how to rewrite some code to accelerate the process?

**Comment by Mathux** [comment]
Hi @YongtaoGe,

I am not a specialist of Blender either but I can try to help. 
It is indeed possible to launch several instances of blender in parallel. 
If you want to render 1000 frames, you may launch 4 process and render 250 frames each.

So what I would do is to change this file:
https://github.com/Mathux/TEMOS/blob/aedf871793bb8f098ce372e3f98b725ccda140ce/temos/render/blender/render.py#L125C9-L125C9
and add a if condition: 
```python
if not start <= index < end: 
    render_current_frame(path)
```
(you still need to load the previous things, to be sure to have a consistent camera)
