### ISSUE TITLE
output in AMASS format

### ISSUE THREAD

**Issue by mtran14** [Mathux/TEMOS#41]
Hello, I would like to use the text-to-motion feature of TEMOS, and I would like the output to be SMPL parameters in AMASS format, containing 'poses' (Tx66D: 22 joints x 3) and 'trans' (Tx3D).  Do you have any suggestions on how I could get that type of output format? The closest thing I can find is RotTransDatastruct in smpl.py, but I'm not sure if that's the correct and the 'rots' is represented as Tx22x3x3. Thank you!

**Comment by Mathux** [comment]
Hello,The rots in RotTransDatastruct (Tx22x3x3) are SMPL pose parameters in matrix format. You just need to convert them to axis angle (with the function matrix_to_axis_angle in temps/tools/geometry.py). You will get a tensor of shape Tx22x3. Then you can reshape it to Tx66.Best,MathisOn 9 Oct 2024, at 00:34, Minh Tran ***@***.***> wrote:﻿
Hello, I would like to use the text-to-motion feature of TEMOS, and I would like the output to be SMPL parameters in AMASS format, containing 'poses' (Tx66D: 22 joints x 3) and 'trans' (Tx3D).  Do you have any suggestions on how I could get that type of output format? The closest thing I can find is RotTransDatastruct in smpl.py, but I'm not sure if that's the correct and the 'rots' is represented as Tx22x3x3. Thank you!

**Comment by mtran14** [comment]
Thank you for your helpful and prompt response. Really appreciate it!
