### ISSUE TITLE
Training on multi-GPU

### ISSUE THREAD

**Issue by Xuehao-Gao** [Mathux/TEMOS#9]
Hi dear author,
   I would like to train the temos on multi-GPU. As shown in Fig.1, It runs well when using one GPU as default. But, when I try to run it on multi-GPU and set the `gpus: 4` in the trainer config file, I meet a _Type Error_  shown in Fig.2. So, I would like to know how to train temos on multi-GPU well.

One GPU Training:
![微信截图_20220610094505](https://user-images.githubusercontent.com/28483420/172975036-c9ee540f-ee93-4448-b60d-1634a2e11d7c.png)

Four GPUs Training:
![微信截图_20220610094621](https://user-images.githubusercontent.com/28483420/172975139-ce7a2f6c-b256-4587-9ee6-02a710ec842e.png)

**Comment by Mathux** [comment]
Hello @Lucky-Maximize,

I just solved this "pickle problem" with this commit: https://github.com/Mathux/TEMOS/commit/3e0efdd8acc253e7144a819c98e755b9e5c4dc1e

Actually, the current code is not designed for GPU-training and it is not working yet. When I will have more time, I will probably investigate and make it work. I need to redesign a bit the data loading, and the metric computation.
